name: HotAirBalloon
author: solo
version: 0.0.3
main: solo\hotairballoon\HotAirBalloon
api: [5.0.0]

commands:
  vehicle:
    description: "HotAirBalloon vehicle commands"
    usage: "/vehicle <registerskin|create>"
    permission: hotairballoon.command

permissions:
  hotairballoon.command:
    description: "Allows using the vehicle command"
    default: op
